include(":app")
include(":features:dogs")
include(":core:navigation")
include(":core:network")
include(":core:database")
include(":common:components")
include(":common:theme")
include(":features:meuModulo")